//
//#include "main.h"
//#include "i2c.h" // Assuming hi2c3 is defined here
//#include "comms.h" // Assuming uart_printf is defined here
//#include "cmsis_os2.h"
//#include <stdio.h>
//#include <string.h>
//
//
//// I2C Handles (auto-generated by STM32CubeIDE)
//// Make sure hi2c3 is defined in your project (e.g., in i2c.c)
//extern I2C_HandleTypeDef hi2c3;
//extern UART_HandleTypeDef huart2; // Or whichever UART you use for uart_printf
//
//// I2C address for the PCA9548A multiplexer (shifted left by 1 for HAL)
//#define MUX_ADDR (0x70 << 1)
//
//// I2C address for the AS5600 encoder (shifted left by 1 for HAL)
//#define AS5600_ADDR (0x36 << 1)
//
//// AS5600 Registers
//#define AS5600_STATUS_REGISTER 0x0B
//#define AS5600_ANGLE_REGISTER 0x0E
//
//// AS5600 Status Register Bits
//#define STATUS_BIT_MH (1 << 5) // Magnet too strong
//#define STATUS_BIT_ML (1 << 4) // Magnet too weak
//#define STATUS_BIT_MD (1 << 3) // Magnet detected
//
//// Buffer for UART messages (if not using a dedicated comms function)
//char uart_buf[100];
//
//// Handle for the semaphore that signals ROS task initialization is complete.
//// This must be defined and created in your main.c
//extern osSemaphoreId_t rosInitSemaphore;
//
//
///**
//  * @brief  Selects a specific channel on the PCA9548A I2C multiplexer.
//  * @param  channel: The channel to select (0-7).
//  * @retval HAL_StatusTypeDef: HAL status of the I2C transmission.
//  */
//HAL_StatusTypeDef selectI2CChannel(uint8_t channel) {
//    if (channel > 7) {
//        return HAL_ERROR; // Invalid channel
//    }
//    uint8_t data = 1 << channel;
//    // The master transmits the channel selection to the multiplexer.
//    return HAL_I2C_Master_Transmit(&hi2c3, MUX_ADDR, &data, 1, 100);
//}
//
//
//
///**
//  * @brief  Function implementing the sensor reading task.
//  * @param  argument: Not used
//  * @retval None
//  */
//void StartSensorTask(void *argument)
//{
//    // --- Wait for ROS Task to Finish Initializing ---
//    uart_printf("Sensor Task: Waiting for ROS initialization...\r\n");
//    // This call will block this task indefinitely until the semaphore is released
//    // by the ROS task, guaranteeing it only runs after ROS is ready.
//    osSemaphoreAcquire(rosInitSemaphore, osWaitForever);
//    uart_printf("Sensor Task: Starting now that ROS is initialized.\r\n");
//
//    // --- Initialization: Check AS5600 Magnet Status ---
//    osDelay(200); // Wait a moment for safety after being unblocked
//    uart_printf("Initializing AS5600 on Channel 0...\r\n");
//
//    if (selectI2CChannel(0) != HAL_OK) {
//        uart_printf("Init failed: Could not select MUX channel 0.\r\n");
//    } else {
//        uint8_t reg = AS5600_STATUS_REGISTER;
//        uint8_t status_data = 0;
//        HAL_StatusTypeDef status;
//
//        // Point to the status register
//        status = HAL_I2C_Master_Transmit(&hi2c3, AS5600_ADDR, &reg, 1, 100);
//        if (status == HAL_OK) {
//            // Read the status register's value
//            status = HAL_I2C_Master_Receive(&hi2c3, AS5600_ADDR, &status_data, 1, 100);
//        }
//
//        if (status != HAL_OK) {
//            uart_printf("Init failed: AS5600 not found on Channel 0.\r\n");
//        } else {
//            // Check the magnet status bits from the read data
//            if ((status_data & STATUS_BIT_MD) == 0) {
//                 uart_printf("ERROR: Magnet not detected! Check sensor placement.\r\n");
//            } else if (status_data & STATUS_BIT_ML) {
//                 uart_printf("Warning: Magnet position is too weak.\r\n");
//            } else if (status_data & STATUS_BIT_MH) {
//                 uart_printf("Warning: Magnet position is too strong.\r\n");
//            } else {
//                 uart_printf("AS5600 Initialized: Magnet detected successfully.\r\n");
//            }
//        }
//    }
//
//    // Give some time for the init messages to be read
//    osDelay(1000);
//
//    // --- Main Sensor Reading Loop ---
//    for (;;)
//    {
//    	if (selectI2CChannel(0) != HAL_OK) {
//            uart_printf("Error: Failed to select MUX channel 0.\r\n");
//        } else {
//            // Point the AS5600 to its angle register
//            uint8_t reg = AS5600_ANGLE_REGISTER;
//            uint8_t angle_data[2] = {0};
//            HAL_StatusTypeDef status;
//
//            // Transmit the register address we want to read from
//            status = HAL_I2C_Master_Transmit(&hi2c3, AS5600_ADDR, &reg, 1, 100);
//
//            if (status == HAL_OK) {
//                // Receive the 2 bytes of angle data
//                status = HAL_I2C_Master_Receive(&hi2c3, AS5600_ADDR, angle_data, 2, 100);
//            }
//
//            // Convert and print the data
//            if (status == HAL_OK) {
//                int rawAngle = (angle_data[0] << 8) | angle_data[1];
//                float degrees = rawAngle * (360.0 / 4096.0);
//                int degrees_whole = (int)degrees;
//			   // Get the first two decimal places
//			   int degrees_fractional = (int)((degrees - degrees_whole) * 100);
//			   // Make sure the fractional part is positive
//			   if (degrees_fractional < 0) {
//				   degrees_fractional *= -1;
//			   }
//
//			   // Print as two integers, with leading zero for the fractional part
//			   uart_printf("Raw: %d\t Degrees: %d.%02d\r\n", rawAngle, degrees_whole, degrees_fractional);
//
//            } else {
//                uart_printf("Error: AS5600 not found on Channel 0.\r\n");
//            }
//        }
//
//		osDelay(1000); // Wait for 1 second before the next reading
//    }
//}
//
